name: "Daily"

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  daily-job:
    name: "Daily Check"
    uses: mParticle/mparticle-workflows/.github/workflows/android-kit-daily.yml@stable